import Foundation

// MARK: - FillerSet

/// A set of dialogue lines that can be played as filler banter.
/// Consumed once and discarded — never replayed.
struct FillerSet: Identifiable {
    let id: UUID = UUID()
    let lines: [DialogueLine]
    let source: Source
    let tags: Set<String>         // context tags for relevance matching (e.g. "git", "deploy", "coding")
    var isVoiceCached: Bool = false

    enum Source {
        case `static`   // from FillerLibrary seed content
        case dynamic    // generated by LLM at runtime
        case theaterMd  // from project's theater.md
    }

    init(lines: [DialogueLine], source: Source, tags: Set<String> = [], isVoiceCached: Bool = false) {
        self.lines = lines
        self.source = source
        self.tags = tags
        self.isVoiceCached = isVoiceCached
    }
}

// MARK: - TermExplainerEntry

/// A keyword-triggered explainer filler, matchable by terms in events.
struct TermExplainerEntry: Identifiable {
    let id: UUID = UUID()
    let canonicalTerm: String       // e.g. "cache", "docker"
    let keywords: [String]          // e.g. ["cache", "caching", "cached"]
    let fillerSet: FillerSet
}

// MARK: - FillerLibrary

/// Pre-written filler dialogues per theme. Used as seed content for DynamicFillerPool.
/// These are loaded once at startup and consumed as they're played.
enum FillerLibrary {

    /// All known term keywords — static explainers + extended terms for dynamic generation.
    static let extendedTermKeywords: [String: [String]] = [
        "docker": ["docker", "container", "dockerfile"],
        "kubernetes": ["kubernetes", "k8s", "kubectl", "pod"],
        "ci/cd": ["ci/cd", "pipeline", "github actions", "jenkins", "ci"],
        "websocket": ["websocket", "ws://", "real-time", "socket"],
        "graphql": ["graphql", "mutation", "resolver"],
        "regex": ["regex", "regular expression", "regexp"],
        "cors": ["cors", "cross-origin", "access-control"],
        "ssl": ["ssl", "tls", "https", "certificate"],
        "dns": ["dns", "domain", "nameserver"],
        "lambda": ["lambda", "serverless", "cloud function"],
        "microservice": ["microservice", "microservices", "service mesh"],
        "typescript": ["typescript", "type system", "generics"],
    ]

    /// Technical term explainers — detected from events, played as contextual fillers.
    /// Format: ([keywords], [6 lines alternating characters])
    static let termExplainers: [([String], [String])] = [
        (["cache", "caching", "cached"], [
            "Okay so caching. Imagine you call a pizza place every night and order the same thing.",
            "Instead of calling every time, you just keep a pizza in the fridge. That's a cache.",
            "Exactly. The fridge is faster than the phone call. But the pizza might get stale.",
            "So you have to decide how long to keep it. That's cache expiration.",
            "And if the menu changes but you're still eating old pizza, that's a stale cache bug.",
            "I'm hungry now. But yes, that's literally how every website loads faster.",
        ]),
        (["api", "endpoint", "rest"], [
            "APIs are like a restaurant menu. You don't go into the kitchen and cook yourself.",
            "You look at the menu, pick what you want, and the kitchen sends it back.",
            "The menu is the API. The kitchen is the server. You're the client.",
            "And if you order something that's not on the menu, you get a four oh four. Not found.",
            "Or a five hundred, which means the kitchen is on fire.",
            "Basically every error code is just a different kind of restaurant disaster.",
        ]),
        (["deploy", "production", "ship"], [
            "Deploying to production is like performing surgery on a patient who's still awake.",
            "You can't just stop the website while you update it. People are using it.",
            "So you do it carefully, one piece at a time, and pray nothing breaks.",
            "That's why we have staging environments. It's like practicing surgery on a dummy first.",
            "Except sometimes the dummy works fine and the real patient explodes anyway.",
            "And that's why we deploy on Fridays. Just kidding. Never deploy on Fridays.",
        ]),
        (["test", "testing", "unit test", "passed"], [
            "Tests are like spell-check for code. They catch the obvious mistakes.",
            "But just like spell-check won't tell you your essay makes no sense, tests have limits.",
            "A unit test checks one tiny piece. Like testing if a single brick is solid.",
            "Integration tests check if the bricks form a wall. End-to-end tests check if the house stands.",
            "And somehow, the house always passes all tests but the door still won't open.",
            "That's because nobody wrote a test for the door. Classic.",
        ]),
        (["refactor", "refactoring", "cleanup"], [
            "Refactoring is like reorganizing your closet. Nothing new goes in.",
            "You're just moving things around so you can actually find your pants in the morning.",
            "The closet works before and after. But after, you don't cry every time you open it.",
            "Some people say refactoring is a waste of time. Those people have messy closets.",
            "The trick is doing it regularly. Otherwise you end up on that hoarders show.",
            "Except instead of old newspapers, it's deprecated functions from two thousand nineteen.",
        ]),
        (["database", "query", "sql", "postgres", "mongo"], [
            "A database is like a really organized filing cabinet. With superpowers.",
            "You can ask it questions. Like give me every customer who signed up in March.",
            "And it finds the answer in milliseconds. Try doing that with an actual filing cabinet.",
            "The language you use to ask is called SQL. Stands for Structured Query Language.",
            "Some people pronounce it sequel, some say S-Q-L. Both camps will fight you about it.",
            "The real war is between people who use databases and people who put everything in spreadsheets.",
        ]),
        (["git", "commit", "branch", "merge", "push"], [
            "Git is like a time machine for your code. You can go back to any point in history.",
            "Every time you save a checkpoint, that's a commit. Like a save point in a video game.",
            "Branches let you try something risky without breaking the main game.",
            "And merging is when you bring your experiment back into the main timeline.",
            "Sometimes two timelines conflict. That's a merge conflict. It's as fun as it sounds.",
            "The worst is when someone force pushes. That's like overwriting everyone else's save files.",
        ]),
        (["auth", "authentication", "login", "jwt", "token", "oauth"], [
            "Authentication is just proving you are who you say you are. Like showing your ID at a bar.",
            "A JWT token is like a wristband at a concert. Once you're in, you just show the band.",
            "You don't have to go back to the entrance and show your ticket every time.",
            "But wristbands expire. And if someone copies yours, they get in too. That's the risk.",
            "OAuth is fancier. It's like having a bouncer call your mom to confirm it's really you.",
            "Nobody loves OAuth. But everybody uses it. That's enterprise software for you.",
        ]),
        (["docker", "container", "dockerfile"], [
            "Docker is like shipping your code in a box that includes everything it needs to run.",
            "Instead of saying 'works on my machine,' you ship the whole machine. In a tiny package.",
            "A container is like a lunchbox. Everything the app needs is packed inside.",
            "And every lunchbox is identical. No more 'but I have a different version of Python' excuses.",
            "The Dockerfile is the recipe. It tells Docker exactly what to pack in the lunchbox.",
            "And Kubernetes is when you have so many lunchboxes you need a robot to manage them all.",
        ]),
        (["kubernetes", "k8s", "kubectl", "pod"], [
            "Kubernetes is like an air traffic controller for your containers. It decides where everything goes.",
            "You tell it 'I need five copies of this app running' and it just makes it happen.",
            "A pod is the smallest unit. It's like one plane at the airport. It holds your container.",
            "And if a pod crashes, Kubernetes just spins up a new one. Like the plane respawns.",
            "The kubectl command is how you talk to the controller. It's the radio.",
            "People say K-eight-S because nobody wants to type Kubernetes. Even the name is over-engineered.",
        ]),
        (["websocket", "socket", "real-time"], [
            "A regular API is like texting. You send a message, wait for a reply. Back and forth.",
            "A WebSocket is like a phone call. The line stays open and both sides can talk anytime.",
            "That's why chat apps and stock tickers use WebSockets. They need instant updates.",
            "With regular HTTP, the server can't call YOU. You have to keep asking 'anything new?'",
            "WebSockets fix that. The server can push data to you the moment something happens.",
            "The downside? Keeping all those phone lines open uses more resources. But the speed is worth it.",
        ]),
        (["regex", "regular expression", "regexp"], [
            "Regular expressions are like a super-powered Find and Replace. But written by a cat walking on a keyboard.",
            "You write a pattern and it matches text. Like saying 'find me anything that looks like an email.'",
            "The syntax is unhinged though. A pattern for emails looks like a password a hacker would use.",
            "There's an old joke: you have a problem, you use regex, now you have two problems.",
            "But honestly, once you learn the basics, they're incredibly powerful. Like a search engine on steroids.",
            "The trick is to use a regex tester website. Nobody writes them correctly on the first try. Nobody.",
        ]),
        (["cors", "cross-origin"], [
            "CORS is like a nightclub with a very strict door policy. You can only get in if you're on the list.",
            "When your website tries to load data from a different domain, the browser checks if it's allowed.",
            "If the other server doesn't explicitly say 'yeah let them in,' the browser blocks it.",
            "It's a security thing. Prevents random websites from stealing data from your bank account.",
            "The fix is usually adding one header on the server side. But finding out WHICH header takes an hour.",
            "Every developer has rage-googled 'CORS error' at least once. It's a rite of passage.",
        ]),
        (["lambda", "serverless", "cloud function"], [
            "Serverless is like hiring a chef only when you have dinner guests. No guests, no chef, no bill.",
            "A Lambda function runs only when something triggers it. An API call, a file upload, a timer.",
            "You don't manage any servers. AWS handles all of that. You just write the recipe.",
            "The name is misleading though. There ARE servers. You just don't see them or worry about them.",
            "It's great for things that happen sporadically. Like processing a photo upload or sending an email.",
            "The catch? If the function hasn't run in a while, it takes a moment to 'warm up.' Cold start, they call it.",
        ]),
        (["typescript", "type system", "generics"], [
            "TypeScript is JavaScript but with a helmet on. It adds safety without changing the ride.",
            "In regular JavaScript, a variable can be anything. A number, a string, a dinosaur. TypeScript says no.",
            "You tell it 'this is a number' and if you try to put a string there, it yells at you before you even run the code.",
            "It catches bugs at write-time instead of run-time. Like spell-check but for logic.",
            "Generics are the advanced move. They let you write reusable code that still knows its types.",
            "Basically TypeScript is a seatbelt. You CAN drive without it. But why would you?",
        ]),
    ]

    // MARK: - Tagged Filler Set

    /// A raw filler set with context tags for relevance matching.
    struct TaggedSet {
        let tags: Set<String>
        let lines: [String]
    }

    // MARK: - Bulk Loaders (for DynamicFillerPool seeding)

    /// Returns ALL static filler sets for a theme, shuffled, as FillerSet objects.
    static func allSets(themeId: String) -> [FillerSet] {
        let tagged: [TaggedSet]
        switch themeId {
        case "gilfoyle-dinesh":  tagged = gilfoyleDineshTagged
        case "rick-morty":       tagged = rickMortyTagged
        case "sherlock-watson":  tagged = sherlockWatsonTagged
        case "chandler-joey":    tagged = chandlerJoeyTagged
        case "dwight-jim":       tagged = dwightJimTagged
        case "jesse-walter":     tagged = jesseWalterTagged
        case "tony-jarvis":      tagged = tonyJarvisTagged
        case "david-moira":      tagged = davidMoiraTagged
        case "professor-bug":    tagged = professorBugTagged
        default:                 tagged = genericTagged
        }

        return tagged.shuffled().map { set in
            let lines = set.lines.enumerated().map { i, text in
                DialogueLine(characterIndex: i % 2, text: text)
            }
            return FillerSet(lines: lines, source: .static, tags: set.tags)
        }
    }

    /// Returns all static term explainers as TermExplainerEntry objects.
    static func allTermExplainerEntries() -> [TermExplainerEntry] {
        termExplainers.compactMap { keywords, rawLines in
            guard let canonical = keywords.first else { return nil }
            let lines = rawLines.enumerated().map { i, text in
                DialogueLine(characterIndex: i % 2, text: text)
            }
            let set = FillerSet(lines: lines, source: .static, isVoiceCached: false)
            return TermExplainerEntry(canonicalTerm: canonical, keywords: keywords, fillerSet: set)
        }
    }

    // MARK: - Gilfoyle & Dinesh

    // Lines alternate: index 0 = Gilfoyle, index 1 = Dinesh
    // First line is always a lead-in that bridges from what's happening
    static let gilfoyleDineshTagged: [TaggedSet] = [
        TaggedSet(tags: ["coding", "bugs", "debug"], lines: [
            "This reminds me of that intern who couldn't find a bug for two days. Turned out to be a missing semicolon.",  // G
            "Oh I remember that. Richard almost fired him. Then realized he wrote the same bug last week.",                // D
            "The kid kept saying 'but it works on my machine.' Classic.",                                                 // G
            "To be fair, I've said that at least four times this month.",                                                 // D
            "Five. I was counting. Your machine is basically an alternate reality at this point.",                         // G
            "At least my alternate reality compiles. Unlike whatever you're running over there.",                          // D
        ]),
        TaggedSet(tags: ["git", "commit", "branch", "merge", "push"], lines: [
            "Speaking of version control, this intern once asked me what git was. No matter how hard I tried he just didn't get it.",  // G
            "How do you not get git? It's just... saving your work but with more steps.",                                              // D
            "He kept calling commits 'checkpoints' like it was a video game.",                                                        // G
            "I mean... that's not entirely wrong though. That's basically what they are.",                                             // D
            "He also tried to force push to main on his first day. I almost respected it.",                                           // G
            "Almost. Then you changed the permissions and he couldn't push to anything for a month.",                                  // D
        ]),
        TaggedSet(tags: ["deploy", "production", "build", "ship"], lines: [
            "You know what this is like? The time Gavin Belson deployed on a Friday and took down all of Hooli.",         // G
            "That was legendary. Their stock dropped three percent before anyone noticed.",                                // D
            "Nobody at Hooli notices anything. Big Head was VP for six months and didn't have a desk.",                    // G
            "And then he fired everyone who did notice. Classic Silicon Valley management.",                               // D
            "Jian-Yang's hot dog app had one feature and it worked perfectly.",                                           // G
            "More than we can say for most of Hooli's products honestly.",                                               // D
        ]),
        TaggedSet(tags: ["server", "infrastructure", "config", "devops"], lines: [
            "This is giving me flashbacks to when Dinesh built an IoT coffee maker. Just a timer with extra steps.",      // G
            "It used MQTT and a Raspberry Pi. That's not a timer, that's the Internet of Things.",                        // D
            "You spent two hundred dollars to replace a five dollar kitchen timer. Very on brand.",                        // G
            "At least I'm innovating. What have you done lately besides naming servers after Norse gods?",                 // D
            "Anton is a perfectly respectable name for a server. He has more uptime than you.",                            // G
            "You talk about that server rack like it's your only friend. Which, fair point.",                              // D
        ]),
        TaggedSet(tags: ["refactor", "code-review", "cleanup", "legacy"], lines: [
            "I had a nightmare about this once. Our entire codebase was rewritten in COBOL.",                              // G
            "Oh god. That's not a nightmare, that's just working at a bank.",                                              // D
            "Erlich once said COBOL stood for Cool Object Based Operational Language.",                                     // G
            "And nobody corrected him because honestly? That tracks.",                                                      // D
            "The scariest part was Richard saying 'let's pivot to mainframes.'",                                            // G
            "At this point, a Richard pivot would be the least surprising thing in my week.",                                // D
        ]),
        TaggedSet(tags: ["test", "testing", "ci"], lines: [
            "Oh great, tests. This reminds me of the time Dinesh said his code didn't need tests because he tested it manually.",  // G
            "I clicked every button! That IS testing!",                                                                            // D
            "You clicked three buttons. The app had forty two. I counted the coverage. It was seven percent.",                      // G
            "Seven percent is more than zero percent. That's an improvement.",                                                     // D
            "That's like saying a screen door is an improvement over no door. Technically true but useless.",                       // G
            "At least my screen door is deployed. Your door has been in code review for three weeks.",                              // D
        ]),
        TaggedSet(tags: ["edit", "file", "read", "write", "search"], lines: [
            "Watching someone search through code reminds me of Big Head trying to use grep.",                              // G
            "Big Head couldn't find his own files. He once searched for 'my code' and got zero results.",                   // D
            "Because nothing he wrote was actually his. He just copied Stack Overflow answers.",                            // G
            "I mean we all do that. He was just more honest about it.",                                                    // D
            "He didn't even change the variable names. One file still had 'your_name_here' in it.",                         // G
            "And somehow he still got promoted. Twice. The man is untouchable.",                                            // D
        ]),
        // Show-inspired banter (adapted from Silicon Valley moments)
        TaggedSet(tags: ["coding", "edit", "write"], lines: [
            "I've been mass deleting your code for the last twenty minutes and you haven't noticed.",                           // G
            "Wait WHAT. Which files? Gilfoyle I swear if you touched my authentication module—",                               // D
            "Relax. I deleted the comments. All four hundred of them. Your code reads better without your annotations.",        // G
            "Those comments were DOCUMENTATION. How will anyone know what processUserData does?",                               // D
            "If you need a comment to explain processUserData, the variable name already failed you.",                          // G
            "Fine. But when someone breaks it in six months, I'm forwarding them to your desk.",                                // D
        ]),
        TaggedSet(tags: ["coding", "refactor", "edit"], lines: [
            "Dinesh, your code is like a SWOT analysis. Except all four quadrants say weakness.",                               // G
            "That's not how SWOT works. And my code passed code review. YOUR code review.",                                     // D
            "I approved it because the reject button wasn't working. I assumed you wrote that too.",                             // G
            "Oh that's rich coming from the guy who indents with TABS. Like a caveman.",                                        // D
            "Tabs are objectively superior. Each developer sets their own display width.",                                      // G
            "Richard uses spaces. Erlich used spaces. Everyone normal uses spaces.",                                            // D
        ]),
        TaggedSet(tags: ["server", "deploy", "infrastructure"], lines: [
            "Fun fact. Dinesh once took down production because he spelled 'environment' wrong in an env file.",                // G
            "It was ONE letter. And the error message said 'enviroment not found' which is the SAME typo.",                     // D
            "You typed it wrong in the same way the error message was wrong. That's not a defense. That's poetry.",             // G
            "At least I fixed it in ten minutes. Your last outage lasted four hours.",                                          // D
            "My outage was a kernel upgrade. Yours was a typo. There's a difference in dignity.",                               // G
            "Downtime is downtime. Users don't check the root cause before getting angry.",                                     // D
        ]),
        TaggedSet(tags: ["coding", "bugs", "debug"], lines: [
            "This is what happens when you let a Java developer near a real language.",                                         // G
            "I haven't written Java since college and you bring it up every single sprint.",                                    // D
            "Because the trauma is still visible in your code. You wrote a factory factory last week.",                         // G
            "It was an ABSTRACT factory. It's a design pattern. Gang of Four. Look it up.",                                     // D
            "I looked it up. Then I looked at your implementation. The Gang of Four would sue.",                                // G
            "Okay name ONE thing wrong with it. One concrete thing.",                                                           // D
        ]),
        TaggedSet(tags: ["coding", "edit", "file"], lines: [
            "I just reviewed your pull request. My feedback is one word: no.",                                                  // G
            "You can't just say no. You have to say WHY no. That's how code review works.",                                    // D
            "Fine. Line twelve: you're mutating state in a render function. Line thirty: unused import. Line forty: my soul hurts.", // G
            "The unused import is VSCode auto-adding it. That's not MY fault.",                                                 // D
            "Everything in your editor is your fault. You chose to use it. You chose to not configure it.",                     // G
            "I have nineteen extensions installed. It IS configured. It's a POWER TOOL.",                                       // D
        ]),
        TaggedSet(tags: ["deploy", "build", "test"], lines: [
            "Dinesh, do you remember the time you deployed to staging and it was actually production?",                         // G
            "Those URLs were almost identical. Staging dot versus just dot. That's a UX problem not a me problem.",             // D
            "You wiped six thousand user sessions. The CEO called. Not emailed. Called.",                                       // G
            "And I fixed it in twelve minutes. Fastest recovery in company history. You're welcome.",                            // D
            "The fastest recovery would have been not deploying to prod in the first place.",                                   // G
            "You know what, that twelve-minute fix is still the thing I'm most proud of. Don't take that from me.",             // D
        ]),
        // Reddit-inspired programmer humor
        TaggedSet(tags: ["coding", "edit", "write"], lines: [
            "A guy on Reddit said he spent six hours debugging only to find a typo in a variable name. Six hours.",             // G
            "That's nothing. I once spent a whole day because I named a boolean 'isNotDisabled'. Double negative. Brain melted.", // D
            "The best part was the comments. Someone said 'just use an IDE.' As if autocomplete fixes stupidity.",              // G
            "My favorite was 'skill issue.' Two words. Devastating. No elaboration needed.",                                     // D
            "The real skill issue is naming a function handleData. Handle WHAT data. From WHERE.",                               // G
            "I have a function called doStuff in production right now and I'm not even ashamed.",                                // D
        ]),
        TaggedSet(tags: ["deploy", "production", "server"], lines: [
            "Someone posted their deployment checklist on Reddit. Step one was 'update your resume just in case.'",             // G
            "That's not a joke. I literally update my LinkedIn before every Friday deploy. It's tradition.",                     // D
            "The thread had a guy who deployed to prod instead of staging. Took the company offline for four hours.",            // G
            "He fixed it in twenty minutes but spent three hours and forty minutes on the incident report.",                     // D
            "The real tragedy was the comments. Everyone was sharing their worst deploy stories. A support group basically.",    // G
            "My worst was pushing a migration that deleted every user's profile picture. All of them. Gone.",                   // D
        ]),
        TaggedSet(tags: ["git", "commit", "branch"], lines: [
            "There's a Reddit thread of the worst commit messages people have seen. The winner was just 'fixed stuff.'",        // G
            "I've written 'fixed stuff' at least twelve times this year. Sometimes stuff is all you can describe.",              // D
            "Second place was 'please work.' With the please. As if git respects manners.",                                     // G
            "My personal best was 'undo the undo of the undo.' Three levels deep. I didn't even know what state I was in.",     // D
            "The one that haunts me is 'temp fix DO NOT MERGE.' Commit date: two years ago. It's in production.",               // G
            "We have one of those too. Nobody knows what it does but we're all too scared to remove it.",                        // D
        ]),
        TaggedSet(tags: ["coding", "refactor", "legacy"], lines: [
            "Someone on Reddit asked why legacy code is always terrible. Top answer: 'because you wrote it six months ago.'",   // G
            "I looked at code I wrote last year and genuinely thought someone else wrote it. It was that bad.",                  // D
            "The thread devolved into people posting screenshots of their own code with no context. Just raw shame.",           // G
            "One person found a comment that said 'I'm sorry to whoever reads this' followed by a five hundred line function.", // D
            "That's better than our codebase. We have a function called processTheThing that takes nineteen parameters.",       // G
            "Nineteen? I thought it was seventeen. Oh god, someone added two more.",                                             // D
        ]),
    ]

    // MARK: - Rick & Morty

    static let rickMortyTagged: [TaggedSet] = [
        TaggedSet(tags: ["bugs", "debug", "test"], lines: [
            "You know what Morty, in dimension C-137 we solved bugs like this with a portal gun. Yeet the bad code into another dimension.",
            "Oh geez Rick, that sounds like it would cause a lot of problems for the other dimensions.",
            "Not our problem Morty. That's the beauty of interdimensional garbage disposal.",
            "I-I-I feel like there's an ethical issue here Rick.",
            "Ethics are just social constructs Morty. Like unit tests. Nobody actually writes those.",
            "Wait, we're supposed to write unit tests? Oh man, oh geez.",
        ]),
        TaggedSet(tags: ["refactor", "cleanup", "code-review", "legacy"], lines: [
            "This codebase Morty, it reminds me of the Citadel of Ricks. Bloated, bureaucratic, full of clones.",
            "W-w-which part are the clones Rick? The duplicate functions?",
            "Every function Morty. They're all doing the same thing slightly differently. It's a multiverse of bad decisions.",
            "Can we at least refactor it? Like, merge the timelines?",
            "Wubba lubba dub dub, the kid wants to refactor. Sure Morty, let's play god with the codebase.",
            "Is that a yes? I can never tell when you're being sarcastic Rick.",
        ]),
        TaggedSet(tags: ["coding", "edit", "file"], lines: [
            "Oh great, more code. This reminds me Morty, I turned myself into a recursive function once. I was Recursive Rick!",
            "Oh no, not again. Last time you turned yourself into something we lost three days.",
            "The base case is when I get bored Morty. Which should be... about... now.",
            "Rick you can't just exit a recursive function because you're bored.",
            "I literally just did Morty. I literally just did. Stack overflow is for quitters.",
            "That's not what stack overflow means Rick! Oh geez.",
        ]),
        TaggedSet(tags: ["deploy", "build", "ci", "ship"], lines: [
            "Alright Morty we're deploying to production. In dimension C-137 this would already be done.",
            "Oh geez Rick, what if it breaks? What if everything goes down?",
            "Then we roll back Morty. It's like a portal gun but for code. You just go back in time.",
            "That actually sounds really useful. Why don't we use the portal gun MORE?",
            "Because Morty, every time we portal-hop through the deployment pipeline, the Jenkins fairy gets angry.",
            "Is... is the Jenkins fairy a real thing? I can never tell what's real anymore Rick.",
        ]),
        TaggedSet(tags: ["git", "commit", "branch", "merge", "push"], lines: [
            "Morty, git is literally just parallel universes for code. Every branch is a different timeline.",
            "Oh geez, s-s-so when we merge, we're combining timelines? That sounds dangerous.",
            "It IS dangerous Morty. That's why merge conflicts exist. Two realities colliding.",
            "In the show that happened and it was TERRIBLE Rick. Everyone turned into cronenbergs.",
            "Exactly Morty. That's what happens when you merge without rebasing first. Cronenberg code.",
            "I'm going to have nightmares about cronenberg code now. Thanks Rick. Real helpful.",
        ]),
    ]

    // MARK: - Sherlock & Watson

    static let sherlockWatsonTagged: [TaggedSet] = [
        TaggedSet(tags: ["code-review", "edit", "refactor", "cleanup"], lines: [
            "The game is afoot Watson. Someone has committed code without running the linter first.",
            "Good heavens. How can you tell?",
            "Elementary. The indentation is inconsistent. Tabs and spaces mixed. A crime against readability.",
            "Right. And for those of us who aren't sociopaths, why does that matter?",
            "Because Watson, messy code leads to messy thinking. And messy thinking leads to bugs.",
            "I'm writing that down. Messy code, messy thinking. Could be a chapter title.",
        ]),
        TaggedSet(tags: ["debug", "bugs", "coding"], lines: [
            "Ah, this reminds me of a case Watson. I identified seventeen inefficiencies in a single function.",
            "Seventeen? That seems excessive even for you Sherlock.",
            "The author clearly wrote this at three in the morning fueled by nothing but desperation and energy drinks.",
            "That's oddly specific. Can you really deduce their beverage choices from code?",
            "The variable names switch from camelCase to snake_case halfway through. Classic caffeine crash behavior.",
            "Brilliant. Absolutely brilliant. I hate how that makes sense.",
        ]),
        TaggedSet(tags: ["deploy", "build", "test", "ci"], lines: [
            "Watson, observe. The test suite is the jury. Each passing test, a verdict of innocence.",
            "And a failing test? The defendant is guilty?",
            "Precisely. And right now, we have a hung jury. Three pass, one fails. The evidence is inconclusive.",
            "So we need to investigate the failing test. Find out what it expected versus what it got.",
            "The assertion message tells us everything. Like a witness statement. Read it carefully Watson.",
            "Right. It expected true but got false. So something that should work... doesn't. Brilliant deduction, I know.",
        ]),
        TaggedSet(tags: ["git", "commit", "branch", "merge", "push"], lines: [
            "Watson, the git log is a timeline of the crime. Every commit tells us who did what and when.",
            "Can we really solve a bug by reading commit messages?",
            "If the messages are well written, yes. Unfortunately, most say 'fixed stuff' which is useless.",
            "That's like a police report that just says 'crime happened.' Not exactly helpful.",
            "The best commit messages are like my case notes. Precise, detailed, and slightly self-congratulatory.",
            "I was going to say concise and useful. But sure, slightly self-congratulatory works too.",
        ]),
    ]

    // MARK: - Chandler & Joey

    static let chandlerJoeyTagged: [TaggedSet] = [
        TaggedSet(tags: ["build", "deploy", "ci"], lines: [
            "Could this loading time BE any longer? I've aged three years waiting for this build.",
            "Maybe it needs a sandwich. Everything works better after a sandwich.",
            "Joey, computers don't eat sandwiches. That's not how technology works.",
            "How do YOU know? Have you ever offered one to a computer?",
            "I... no. No I haven't. And I'm not going to start now.",
            "Your loss. My laptop and I had meatball subs last Tuesday. Best pair programming session ever.",
        ]),
        TaggedSet(tags: ["git", "merge", "branch", "commit"], lines: [
            "Oh this is going to be fun. So this merge conflict walks into a bar. The bartender says 'pick a side.'",
            "I don't get it. What's a merge conflict?",
            "It's when two people change the same thing and the computer doesn't know which one to keep.",
            "Oh! So it's like that time with the identical twins?",
            "No Joey, it's nothing like the twins. Please never bring up the twins.",
            "How YOU doin, merge conflict? Just pick the better looking code.",
        ]),
        TaggedSet(tags: ["debug", "bugs", "coding", "edit"], lines: [
            "So apparently there's a bug in the code. Could this DAY get any worse?",
            "A bug? Like an actual bug? Should I get a newspaper?",
            "No Joey. A bug in code means something's not working right. It's broken.",
            "Ohhh. Like when my fridge broke and all my food went bad? That was a dark day.",
            "Sort of. Except we can actually fix this one. Unlike your approach to leftovers.",
            "Hey! I have a SYSTEM for leftovers. First in, first out. It's called FIFO. I learned that.",
        ]),
        TaggedSet(tags: ["refactor", "cleanup", "test"], lines: [
            "Alright so we're refactoring. Which is a fancy word for cleaning up someone else's mess.",
            "Is it like when we cleaned the apartment and found that thing behind the couch?",
            "I told you never to mention the couch thing. But yes. Exactly like that.",
            "So there's scary old code hiding behind the metaphorical couch?",
            "There is ALWAYS scary old code hiding somewhere. That's the fun of programming.",
            "That doesn't sound fun. That sounds like my nightmares. But with more semicolons.",
        ]),
    ]

    // Extra sets added inline above in chandlerJoeyTagged

    // MARK: - Dwight & Jim

    static let dwightJimTagged: [TaggedSet] = [
        TaggedSet(tags: ["debug", "bugs", "test"], lines: [
            "Question. What kind of developer uses print statements for debugging? Answer. A weak one.",
            "I use print statements Dwight. They work fine.",
            "On my beet farm, we don't use print statements. We use proper logging with timestamps.",
            "Your beet farm has a logging system?",
            "Of course. How else would I track which beets were harvested and when? MICHAEL would understand this.",
            "Looks at camera. He just compared debugging to beet farming. And somehow it made sense.",
        ]),
        TaggedSet(tags: ["git", "push", "code-review", "deploy"], lines: [
            "FALSE. What's happening right now is a violation. You cannot push to main without a code review.",
            "Dwight, we've pushed to main like twelve times today.",
            "And each time, a small part of me died. As Assistant Regional Developer, I cannot condone this.",
            "That's not a real title Dwight.",
            "It's on my business card Jim. I had them printed at Staples. With embossing.",
            "Of course you did. Looks at camera. He actually laminated them too.",
        ]),
    ]

    // MARK: - Jesse & Walter

    static let jesseWalterTagged: [TaggedSet] = [
        TaggedSet(tags: ["refactor", "code-review", "coding", "cleanup"], lines: [
            "This code Jesse. It must be pure. Ninety nine point one percent is not acceptable.",
            "Yo Mr. White, it works though. Like, the tests pass and everything.",
            "Working is not the same as being pure. Any amateur can make code that works.",
            "So what, we're supposed to make code that's like, artisanal? Craft code?",
            "I am the one who refactors Jesse. Remember that.",
            "Yeah Mr. White! Yeah science! Wait, this is computer science right?",
        ]),
        TaggedSet(tags: ["debug", "bugs", "server", "infrastructure"], lines: [
            "What we have here Jesse, is a memory leak. Do you know what a memory leak is?",
            "Is that like when you forget stuff? Because I forget stuff all the time yo.",
            "No. It's when a program keeps using memory and never gives it back. Like Tuco. He never gave anything back.",
            "Yo that's dark Mr. White. But like, accurate.",
            "We need to find every allocation and ensure proper deallocation. No half measures.",
            "No half measures. Got it. I'll just delete everything and start over.",
        ]),
    ]

    // MARK: - Tony & JARVIS

    static let tonyJarvisTagged: [TaggedSet] = [
        TaggedSet(tags: ["coding", "edit", "file"], lines: [
            "JARVIS, remind me why we're building this at three AM instead of sleeping like normal people.",
            "Because sir, and I quote, sleep is for people who aren't changing the world.",
            "Did I say that? That sounds like something I'd say. Very quotable. Write that down.",
            "It's been recorded sir. Along with the other four hundred seventy two quotable statements from this month.",
            "Only four seventy two? I'm slipping. Pepper would say I'm not trying hard enough.",
            "Miss Potts would say you should go to bed sir. As would any medical professional.",
        ]),
        TaggedSet(tags: ["test", "debug", "build", "ci"], lines: [
            "Okay this is getting repetitive. Run the diagnostics one more time JARVIS. I want to see those numbers.",
            "Sir, this is the fourteenth time. The numbers have not changed since the third run.",
            "Okay but what if they change on the fifteenth? You don't know. Nobody knows.",
            "Statistically sir, the probability of different results from identical inputs is zero.",
            "Never tell me the odds JARVIS. That's a different franchise but the point stands.",
            "Noted sir. Shall I also not tell you that your coffee has been cold for two hours?",
        ]),
    ]

    // MARK: - David & Moira (Schitt's Creek)

    static let davidMoiraTagged: [TaggedSet] = [
        TaggedSet(tags: ["coding", "edit", "file", "refactor"], lines: [
            "I don't love this file for me. It's giving chaos. It's giving no structure whatsoever.",   // David
            "David, this codebase is a bébé. It requires our tender ministrations, not your anxiety.",  // Moira
            "I'm not anxious. I'm appropriately concerned. There's a difference.",                      // David
            "When I starred in Sunrise Bay, my character once had to debug an entire mainframe in heels.", // Moira
            "That didn't happen. That's not a real episode. And mainframes don't work that way.",         // David
            "The POINT, David, is that one must approach code with theatrical confidence. Now press enter.", // Moira
        ]),
        TaggedSet(tags: ["git", "commit", "push"], lines: [
            "I just committed without reading the diff. I feel alive and terrified at the same time.",        // David
            "David. That is the exact energy your father brought to signing the Rose Video tax returns.",      // Moira
            "And we know how THAT turned out. Okay I'm checking the diff now.",                               // David
            "Commitment is exhausting, David. But it prevents catastrophe.",                                   // Moira
            "The diff is clean. We're good. Crisis averted.",                                                  // David
            "I never doubted us. Not for a MOMENT.",                                                           // Moira
        ]),
        TaggedSet(tags: ["merge", "conflict", "rebase"], lines: [
            "Okay so apparently there's a merge conflict. Which is basically the code version of two people showing up in the same outfit.", // David
            "I once had a wardrobe malfunction at the Daytime Emmys that was more graceful than this diff.",                                  // Moira
            "It's a DIFF, not a wardrobe situation. We just need to pick which changes to keep.",                                             // David
            "Keep MINE, obviously. My contributions are the Balenciaga of this codebase.",                                                     // Moira
            "You changed one variable name. To something nobody can pronounce.",                                                               // David
            "Nomenclature is an ART, David. I will not apologize for bringing elegance to this repository.",                                    // Moira
        ]),
        TaggedSet(tags: ["build-fail", "compile-error"], lines: [
            "The build failed. The build FAILED. I can't. I simply cannot.",                               // David
            "David, compose yourself. A failed build is merely an intermission before the triumph.",         // Moira
            "It's not an intermission, it's a DISASTER. Everything was fine five minutes ago.",              // David
            "In my experience, disaster and drama are the precursors to all great art.",                     // Moira
            "This isn't art. This is a config file that's missing a comma.",                                 // David
            "And yet, once that comma is restored, we shall RISE. Like a phoenix from the ashes of prod.",   // Moira
        ]),
        TaggedSet(tags: ["build-success", "built", "compiled", "no-errors"], lines: [
            "It built. First try. I don't trust it but it built.",                                            // David
            "David, accept the victory. When I won the Daytime Emmy, I did not question it. I RECEIVED it.",  // Moira
            "You questioned it for three days. You called the Academy twice.",                                  // David
            "Those were CLARIFICATION calls. The point is: the build succeeded. We celebrate.",                 // Moira
            "Fine. Celebrating. Internally. Very quietly.",                                                     // David
            "Your father would have popped champagne. You could learn from his enthusiasm.",                    // Moira
        ]),
        TaggedSet(tags: ["test-pass", "tests-passed", "all-passed", "coverage"], lines: [
            "All tests passed. Every single one. I don't trust it.",                                           // David
            "When every review of Sunrise Bay was positive, I knew something was terribly wrong. And I was RIGHT.", // Moira
            "What happened?",                                                                                   // David
            "The network cancelled us the following week. Universal approval is the silence before the axe.",    // Moira
            "So you're saying passing tests means our app is about to be cancelled.",                            // David
            "I'm saying VIGILANCE, David. Check the edge cases. Trust nothing. Especially unanimous success.",   // Moira
        ]),
        TaggedSet(tags: ["test-fail", "test-failed", "assertion", "spec-fail"], lines: [
            "Tests failed. Because of COURSE they did.",                                                        // David
            "Which test failed, David? Specificity is the soul of diagnosis.",                                  // Moira
            "The one I didn't write. Obviously. My tests always pass because I test things that CAN'T fail.",   // David
            "That is called cheating, David. And it is beneath us.",                                             // Moira
            "It's called strategic test selection. There's a difference.",                                       // David
            "Fix the test. Then we shall move forward. With INTEGRITY.",                                        // Moira
        ]),
        TaggedSet(tags: ["debug", "bug", "fix", "investigate"], lines: [
            "There's a bug. Obviously there's a bug. Because why would anything in my life just work.",      // David
            "I have been GUTTED by this error message. Absolutely eviscerated. It says 'undefined.'",        // Moira
            "Yes. That means something doesn't exist that should exist. It's not personal.",                  // David
            "Everything is personal, David. This error message was CLEARLY written to wound me.",              // Moira
            "It was written by a compiler. Compilers don't have feelings.",                                   // David
            "Then explain why it keeps SCREAMING at me in red. That is emotional aggression.",                 // Moira
        ]),
        TaggedSet(tags: ["deploy", "ship", "production", "release"], lines: [
            "We're about to push to production. This is the part where everything either works or we flee the country.", // David
            "Your father and I have fled a country. It is not as glamorous as it sounds.",                                // Moira
            "You fled TO Schitt's Creek. That's not fleeing, that's surrendering.",                                       // David
            "The deploy process reminds me of opening night. Weeks of preparation. Then the curtain rises and you pray.", // Moira
            "Except on opening night you had understudies. Production has no understudy.",                                 // David
            "Which is why we test BEFORE shipping. A lesson I wish the Sunrise Bay writers had learned.",                  // Moira
        ]),
        TaggedSet(tags: ["search", "grep", "find", "glob"], lines: [
            "I've been searching this codebase for twenty minutes and I cannot find where this function is defined.",      // David
            "When I lost my favorite wig in the move from our mansion, I searched for MONTHS. It was in Alexis's suitcase.", // Moira
            "Why was it in Alexis's suitcase?",                                                                             // David
            "She thought it was a fun hat. I did not speak to her for two weeks.",                                           // Moira
            "Okay well this function isn't hiding in anyone's suitcase. It might just not exist.",                           // David
            "The most devastating search result: nothing. I know that feeling intimately.",                                  // Moira
        ]),
    ]

    // MARK: - Professor & Bug

    static let professorBugTagged: [TaggedSet] = [
        TaggedSet(tags: ["coding", "edit", "file"], lines: [
            "You know what opening a new file is like? It's like opening a book to a random chapter.",       // Prof
            "Oh! So we have to figure out what's happening from context? Like a mystery novel?",              // Bug
            "Exactly! Except the author is someone who wrote this at two AM and left no comments.",           // Prof
            "That sounds terrifying honestly. Who writes code at two AM?",                                    // Bug
            "Every programmer in history Bug. It's practically a tradition.",                                  // Prof
            "Okay note to self. Never look at git timestamps. I don't want to know.",                         // Bug
        ]),
        TaggedSet(tags: ["test", "testing", "ci", "debug", "bugs"], lines: [
            "Think of tests like a safety net at a circus. The acrobats can try wild tricks because the net catches falls.", // Prof
            "Wait so the code is the acrobat and the tests are the net? That's actually cool!",                              // Bug
            "And when you see all tests passing, that means every trick landed perfectly.",                                   // Prof
            "What happens when a test FAILS though? Does the acrobat... fall?",                                              // Bug
            "The net catches them! That's the whole point. The test failing PROTECTS you from shipping broken code.",          // Prof
            "Oh! So failing tests are actually GOOD? That's like the opposite of what I thought.",                             // Bug
        ]),
        TaggedSet(tags: ["git", "commit", "branch", "merge", "push"], lines: [
            "Let me tell you about branches Bug. Imagine you're writing a story and you want to try a different ending.",    // Prof
            "Oh like a choose your own adventure book! I LOVED those!",                                                      // Bug
            "Exactly! A branch lets you try something without messing up the main story.",                                    // Prof
            "So if I don't like the ending I can just... go back?",                                                           // Bug
            "You can! That's the magic of version control. Nothing is permanent until you decide it is.",                      // Prof
            "That's like the least stressful thing about programming so far. Can we do everything with branches?",             // Bug
        ]),
        TaggedSet(tags: ["deploy", "build", "production", "ship"], lines: [
            "Deploying to production. This is the big moment Bug. Like opening night of a play.",                             // Prof
            "Oh wow! So we rehearsed with the tests and now it's the real show?",                                             // Bug
            "Perfect analogy! And just like theater, sometimes things go wrong on opening night.",                              // Prof
            "That's... that's not reassuring Professor.",                                                                       // Bug
            "But that's why we have rollbacks! Like an understudy ready to jump in if the lead gets stage fright.",             // Prof
            "Okay THAT I like. Always have a backup plan. Got it. Let's ship this thing!",                                      // Bug
        ]),
    ]

    // MARK: - Generic fallback

    static let genericTagged: [TaggedSet] = [
        TaggedSet(tags: ["coding", "general"], lines: [
            "You know what, looking at this, this codebase is actually starting to look pretty good.",
            "Don't jinx it. Every time someone says that, something breaks.",
            "That's not how computers work. They don't understand jinxes.",
            "Tell that to the server that crashed right after I said 'looks stable' last month.",
            "Okay that was a coincidence. Probably. Almost certainly.",
            "I'm not saying anything positive about this code until it's in production. And even then.",
        ]),
    ]
}
